### PR TITLE
Linted

### PR DESCRIPTION
**Pull request by evaherrada**

### CODE REVIEW

**Comment by tannewt** [comment]
Thanks for picking this up! I think python needs to be bumped to 3.7. (We should do this in cookiecutter too.)

**Comment by evaherrada** [comment]
@tannewt Looks like it's passing now except for the docs

**Comment by tannewt** [comment]
Want to fix those too? I think it may need a mock.

**Comment by evaherrada** [comment]
Ok so I'm not really sure how to fix the const one

**Comment by jposada202020** [comment]
@dherrada I have not test this, but put the library in the interphinx_mapping solve some issues like that for my in the past.

**Comment by jposada202020** [comment]
Not sure what you see in the pre-commit but
Mock are used to mock imports

And interphinx_mapping is used to look for reference in the documentation when the CI is building with autodoc. so depends on where you are failing.. could be one or the other

**Comment by evaherrada** [comment]
Ah ok. Thanks for explaining that

**Comment by jposada202020** [comment]
@dherrada I think we could close this one in favor of #2 , :)

**Comment by evaherrada** [comment]
Definitely. Thanks for taking care of that

**Pull request closed without merging**
